#!/bin/sh

echo "Cleaning image..."

rm -Rf \
  /tmp/* \
  /var/cache/apk/* \
  /var/tmp/* \
  /var/lib/apt/lists/* \
  /var/log/alternatives.log \
  /var/log/apt/ \
  /var/log/bootstrap.log \
  /var/log/btmp \
  /var/log/dpkg.log \
  /var/log/faillog \
  /var/log/fsck/ \
  /var/log/lastlog \
  /var/log/wtmp \
  ~/.cache/pip

find /var/cache/ ! -type d -exec rm '{}' \;

echo "Image cleaned."
